### ISSUE TITLE
HTML body support

### ISSUE THREAD

**Issue by opichals** [Apifier/act-send-mail#1]
Having the opportunity to send HTML would be very nice. Mailgun supports it via [the 'html' option](http://mailgun-documentation.readthedocs.io/en/latest/api-sending.html#sending).

**Comment by drobnikj** [comment]
Hi @opichals, thanks, you are right, we'll add it.

**Comment by opichals** [comment]
Thanks!

**Comment by opichals** [comment]
Could you please publish a new release so that it can be used from the Actor area?

**Comment by drobnikj** [comment]
@opichals I builded new version of public act https://www.apify.com/apify/send-mail, if you use this act, it should work. Let me know
